---
title: "L04 `dplyr` 数据变换"
author: "曾永艺"
date: "2020年12月10日"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: false
    df_print: "tibble"
description: >
  这是厦门大学管理学院财务学系 **“量化金融与金融编程”** 
  课程 _“第4讲 `dplyr` 数据变换”_ 的配套练习。
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(testwhat)
library(nycflights13)
library(tidyverse)
options(tibble.print_max = 6, tibble.print_min = 4)
knitr::opts_chunk$set(echo = FALSE)
tutorial_options(exercise.timelimit = 60, 
                 exercise.checker = testwhat_learnr)

```


## `r emo::ji("book")` 基础概念题

以下选择题用来测试同学们对本讲所讲基础概念和核心函数的理解和掌握情况。

```{r quiz}
quiz(
  question("1 构成 `dplyr` 包数据处理语言基本操作的函数包括：",
           answer("`filter()`", correct = TRUE),
           answer("`arrange()`", correct = TRUE),
           answer("`mutate()`", correct = TRUE),
           answer("`subset()`"),
           answer("`select()`", correct = TRUE),
           answer("`summarise()`", correct = TRUE),
           answer("`group_by()`", correct = TRUE),
           correct = "正确！",
           incorrect = "错误！参见 _R数据科学_ 的3.1.3小节。",
           allow_retry = TRUE,
           random_answer_order = TRUE
  ),
  question("2 以下哪些命令是对数据表的行（样本）进行操作的？",
           answer("`filter()`", correct = TRUE),
           answer("`arrange()`", correct = TRUE),
           answer("`mutate()`"),
           answer("`transmute()`"),
           answer("`select()`"),
           answer("`slice()`", correct = TRUE),
           correct = "Great！",
           incorrect = "错误，请重试！",
           allow_retry = TRUE,
           random_answer_order = TRUE
  ),
  question("3 以下哪些命令与数据表的列（变量）操作有关？",
           answer("`filter()`"),
           answer("`arrange()`"),
           answer("`mutate()`", correct = TRUE),
           answer("`transmute()`", correct = TRUE),
           answer("`select()`", correct = TRUE),
           answer("`rename()`", correct = TRUE),
           correct = "Excellent！",
           incorrect = "错误，请重试！",
           allow_retry = TRUE,
           random_answer_order = TRUE
  ),
  question("4 以下关于 `dplyr` 包中函数说法正确的有：",
           answer("`summarise()` 中支持向量化的汇总函数，如 `log()`。"),
           answer("`mutate()` 总是将新变量添加在数据集的最前面。"),
           answer("`transmute()` 仅保留新变量。", correct = TRUE),
           answer("`select()` 可在选择变量的同时对变量进行重命名。", 
                  correct = TRUE),
           answer("`group_by()` 生成分组数据集，可能会对后续的数据操作产生影响，
           必要时可用 `ungroup()` 取消分组设定。", 
                  correct = TRUE),
           correct = "漂亮！",
           incorrect = "错误，请重试！",
           allow_retry = TRUE,
           random_answer_order = TRUE
  ),
  question("5 以下关于多表操作说法正确的有：",
           answer("数据处理实践中最常用的合并式连接命令为 `left_join()`。", 
                  correct = TRUE),
           answer("`semi_join()` 和 `anti_join()` 完成的是筛选式连接。",
                  correct = TRUE),
           answer("`*_join()` 族命令的 `on` 参数用来设定连接所用的键变量，
           支持灵活多样的设定。"),
           answer("`bind_cols()` 基于行序对多个数据集进行横向合并，
           无需指定键变量。", correct = TRUE),
           answer("`bind_rows()` 基于变量名对多个数据集进行纵向合并。", 
                  correct = TRUE),
           correct = "答对了！给你点赞！",
           incorrect = "错误，请重试！",
           allow_retry = TRUE,
           random_answer_order = TRUE
  ),
  question("6 以下关于 `dplyr` 包优点概括正确的有：",
           answer("`dplyr` 以一组简洁清晰的动词函数来处理常见的数据操作任务。", 
                  correct = TRUE),
           answer("`dplyr` 核心函数的第一个参数为数据集，返回值也为数据集，
           能很好支持管道操作 `%>%`。", correct = TRUE),
           answer("`dplyr` 能通过接口包（如 `dbplyr` 和 `dtplyr`）以相同的函数
           接口操作其他常见的数据库（如 `SQLite`）和 R 数据结构（如 
           `data.table`）。", correct = TRUE),
           answer("`dplyr` 通过 `C++` 实现很多关键的底层代码，从而实现对内存中
           数据的高效运算。", correct = TRUE),
           correct = "Bingo！",
           incorrect = "错误，请重试！",
           allow_retry = TRUE,
           random_answer_order = TRUE
  ),
  caption = "不定项选择题"
)

```

<br>

### `r emo::ji("raising_hand_woman")` 提交不定项选择题的答案

请同学们点击下面的 [Generate] 按钮在方框中生成答案的 hash 码，然后点击方框右上角上的复制按钮，并将得到的hash码直接粘贴到 [腾讯在线收集表QFwR-L04](https://docs.qq.com/form/page/DRm9vTENiVHRUWHhI)中。

```{r context="server"}
learnrhash::encoder_logic()
```

```{r encode, echo=FALSE}
learnrhash::encoder_ui(ui_before = NULL)
```


## `r emo::ji("woman_technologist")` 上机实操练习

接下来请你在 RStudio 的控制台 Console 中键入如下代码调出本讲练习的 `RMarkdown` 文档（`L04-lab.Rmd`），根据提示完成上机实操练习。

```
qfwr::qfwr_lab("L04")

```

